trigger:
  branches:
    include:
      - main

pool:
  name: laptopAsAgent

steps:
- task: NodeTool@0
  displayName: 'Use Node.js 18.x'
  inputs:
    versionSpec: '18.x'

- script: npm install
  displayName: 'Install dependencies'
  workingDirectory: FrontEndApp/my-app

- script: npm run build
  displayName: 'Build React app'
  workingDirectory: FrontEndApp/my-app

- task: PublishBuildArtifacts@1
  displayName: 'Publish React build'
  inputs:
    pathToPublish: 'FrontEndApp/my-app/build'
    artifactName: 'react-build'
